Repository CMU-313/fall-2021-hw2-team-mant, pull requests merged in 2021-10, with the labels that each got.

#21 connected an html file to views.py
  mayan/apps/dashboard/templates/test.html
  mayan/apps/dashboard/views.py
Labels: enhancement

#26 added a graph for student data
  docker/Dockerfile
  mayan/apps/dashboard/templates/studentgraph.png
  mayan/apps/dashboard/templates/test.html
Labels: enhancement

#27 updated read me documentation
  mayan/apps/dashboard/README.md
Labels: documentation

#28 added the reviewer graph and finished documentation
  mayan/apps/dashboard/README.md
  mayan/apps/dashboard/templates/Reviewer_Data.png
  mayan/apps/dashboard/templates/test.html
Labels: documentation, enhancement
